# Generated by Django 5.2.5 on 2025-08-19 08:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('recipient_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='monthlyEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_day', models.IntegerField()),
                ('scheduled_time', models.TimeField(default=datetime.time(9, 0))),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('scheduled_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_email', to='mailer.scheduledemail')),
            ],
        ),
        migrations.CreateModel(
            name='hourlyEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.TimeField(default=datetime.time(9, 0))),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('scheduled_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_email', to='mailer.scheduledemail')),
            ],
        ),
        migrations.CreateModel(
            name='Emailsender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('scheduled_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emailsender', to='mailer.scheduledemail')),
            ],
        ),
        migrations.CreateModel(
            name='dailyEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.TimeField(default=datetime.time(9, 0))),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('scheduled_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_email', to='mailer.scheduledemail')),
            ],
        ),
        migrations.CreateModel(
            name='weeklyEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_day', models.CharField(max_length=10)),
                ('scheduled_time', models.TimeField(default=datetime.time(9, 0))),
                ('sent_time', models.DateTimeField(auto_now_add=True)),
                ('scheduled_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_email', to='mailer.scheduledemail')),
            ],
        ),
    ]
